version: "3.7"
    
services:
  db:
    image: mysql/mysql-server:8.0.23
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: ggl
      MYSQL_USER: ggl
      MYSQL_PASSWORD: 1234
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: ./ggl
    image: ggl_app
    container_name: ggl_app
    restart: always
    ports:
      - 8000:8000
    expose:
      - 8000
    links:
      - db:db
    depends_on:
      db:
        condition: service_healthy

  migration:
    image: ggl_app
    command: flask db upgrade
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy  
